import '../models/bookModel.dart';

 List<BookModel> bookList = [
   BookModel(id: 1, imageUrl: 'assets/images/book1.jpg', title: 'The Edge',read: 44,rating: 5,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
   BookModel(id: 2, imageUrl: 'assets/images/book2.jpg', title: 'over Land',read: 65,rating: 4.5,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
   BookModel(id: 3, imageUrl: 'assets/images/book3.jpg', title: '365 Days',read: 0,rating: 3,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
   BookModel(id: 3, imageUrl: '', title: '',read: 0,rating: 3,price: 12,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),

];

List<BookModel> wishList = [
  BookModel(id: 4, imageUrl: 'assets/images/book4.jpg', title: 'All This Time',read: 44,rating: 5,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 5, imageUrl: 'assets/images/book5.jpg', title: 'Harry Potter',read: 65,rating: 3.5,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 6, imageUrl: 'assets/images/book6.jpg', title: 'Blood Meets',read: 0,rating: 3,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 7, imageUrl: 'assets/images/book7.jpg', title: 'Galaxy',read: 44,rating: 2,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 8, imageUrl: 'assets/images/book8.jpg', title: 'Anya',read: 65,rating: 4.5,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 9, imageUrl: 'assets/images/book9.jpg', title: 'Falling Star',read: 0,rating: 1.5,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 10, imageUrl: 'assets/images/book10.jpg', title: 'Amazing book',read: 44,rating: 5,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 11, imageUrl: 'assets/images/book11.jpg', title: 'Harry potter',read: 65,rating: 4.5,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 12, imageUrl: 'assets/images/book12.jpg', title: 'World ',read: 0,rating: 3,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),
  BookModel(id: 13, imageUrl: 'assets/images/book13.jpg', title: 'Night',read: 0,rating: 3,price: 10,info:' Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry'),


];